### ISSUE TITLE
Potentially eliminate haltF

### ISSUE THREAD

**Issue by AndyZe** [UTNuclearRoboticsPublic/compliant_control#1]
I'm going to open some issues to be reviewed when you have time.

First, I still think it's easy to get these 2 confused. If condF is specified, it overrides haltF, right? So are both needed? I think you could get rid of haltF.

**Comment by nsnitish** [comment]
I think you are right. Moving the haltF a layer deeper only as a safety if one [needs to use it explicitly](https://github.com/UTNuclearRoboticsPublic/compliant_control/blob/a46842b30ebc27967ffa5796bccd42f604dcd952/include/compliant_control.h#L75).
