### ISSUE TITLE
Automatically determine the 'b' parameter

### ISSUE THREAD

**Issue by AndyZe** [UTNuclearRoboticsPublic/compliant_control#2]
I think you could automatically calculate b like this:

vel_compl=b*F   ==>   b=vel_compl/F

Plug in vel_compl=vel_nom so the robot stops at F_threshold:
b = vel_nom/F_threshold

Then the robot should naturally halt when its velocity drops to zero.

**Comment by nsnitish** [comment]
This can be a problem if we need to have compliant motion in different directions(with v_nom = 0) while having controlled motion in one direction.
